set(_CATKIN_CURRENT_PACKAGE "oculus_rviz_plugins")
set(oculus_rviz_plugins_MAINTAINER "David Gossow <dgossow@willowgarage.com>")
set(oculus_rviz_plugins_DEPRECATED "")
set(oculus_rviz_plugins_VERSION "0.0.8")
set(oculus_rviz_plugins_BUILD_DEPENDS "oculus_sdk" "libogre-dev" "libqt4-dev" "libqt4-opengl-dev" "boost" "rviz" "tf" "roscpp")
set(oculus_rviz_plugins_RUN_DEPENDS "oculus_sdk" "libogre-dev" "libqt4-dev" "libqt4-opengl-dev" "boost" "rviz" "tf" "roscpp")
set(oculus_rviz_plugins_BUILDTOOL_DEPENDS "catkin")